### PR TITLE
Pipeline: Install precise version of the dependencies

### PR DESCRIPTION
**Pull request by kit-ty-kate**
The CI doesn't install depexts of test dependencies, this PR fixes this issue

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I was wrong on what was going wrong. This should now fix the pipeline.

The problem was that only the packages name were gotten and installed but some depext might be changed/added/removed between versions.

**Comment by talex5** [comment]
Is this thing with `--dry-run` just the same as using `--show-actions` and `awk '/- install/{print $3 "." $4}'`?

**Comment by kit-ty-kate** [comment]
probably yes, I'm not really a awk expert but yes it's to get packages of the form `name.ver`

**Comment by talex5** [comment]
My way doesn't work because sometimes there's a star at the end. Your dry run system seems to work nicely though!

**Pull request merged**
